[build]
buildCommand = "chmod +x gradlew && ./gradlew clean build -x check -x test -Pproduction && ls -la build/libs/"

[deploy]
startCommand = "java $JAVA_OPTS -jar -Dserver.port=$PORT build/libs/*.jar"